### ISSUE TITLE
Errors on empty array destructuring

### ISSUE THREAD

**Issue by turadg** [sgilroy/async-await-codemod#2]
For example,
```
}).then(([, session]) => {
```

**Comment by sgilroy** [comment]
@turadg Can you please provide a more complete example?

I tested with the following, and there was no error from the code mod:
```js
function arrayDestructuring() {
  return b().then(([, destructuredArrayElement]) => {
    return destructuredArrayElement.d;
  });
}
```

Result:
```js
async function arrayDestructuring() {
  const [, destructuredArrayElement] = await b();
  return destructuredArrayElement.d;
}
```

**Comment by turadg** [comment]
Sorry, can't find the example anymore. But I did file a couple more detailed bug report.

FWIW, here's the success rate on my repo,
```
136 errors
2324 unmodified
2 skipped
6 ok
```

**Comment by sgilroy** [comment]
@turadg Please provide details if you can reproduce.
